### ISSUE TITLE
[Dev] 场地申请取消功能

### ISSUE THREAD

**Issue by morenyang** [nasahq/workbench#5]
**This issues is about a**

- [x] Feature
- [ ] Bugfix

## Dev Feature & Bug

**Feature & Bug**

用户想要场地申请提交后的取消功能。在用户打开 _自己提交_ 的申请详情后，可以在一票申请状态为Accept前取消。

**Deadline**

**Comment by morenyang** [comment]
## Activity Status

- 0 pending
- 1 accepted
- 2 rejected
- 3 canceled

**Comment by reeeexchen** [comment]
### Commit
- provide /apply/cancel/{applyId}
- wait for front-end integrated

**Comment by reeeexchen** [comment]
## Done
