### ISSUE TITLE
[Dev] 场地申请状态标签

### ISSUE THREAD

**Issue by morenyang** [nasahq/workbench#7]
**This issues is about a**

- [x] Feature
- [ ] Bugfix

## Dev Feature & Bug

**Feature & Bug**

为申请的添加关于状态的tag。

**Deadline**

**Comment by morenyang** [comment]
@reeeexchen add `status` field to `Activity` Model

**Comment by reeeexchen** [comment]
## Commit
- provide /apply/audit
- wait for front-end integrated
- logical need to discuss

**Comment by morenyang** [comment]
新建活动后`status`应为0 而不是null

**Comment by reeeexchen** [comment]
## Commit
- fix the status = null problem
- wait for front-end integrate

**Comment by morenyang** [comment]
> ## Commit
> * fix the status = null problem
> * wait for front-end integrate

Still not working

**Comment by morenyang** [comment]
Add condition in `ActivityController` or `ActivityApplyServiceImpl` ?

**Comment by reeeexchen** [comment]
## Commit
- fixed
